name: Tag

on:
  push:
    branches: [main, dev]

jobs:
  tag:
    name: Semantic Release Tag
    runs-on: ubuntu-22.04
    outputs:
      new: ${{ steps.semantic.outputs.new-release-published }}
      version: ${{ steps.semantic.outputs.release-version }}

    steps:
      - uses: actions/checkout@v3

      - name: Tag Semantic Release Version
        id: semantic
        uses: codfish/semantic-release-action@v3
        with:
          branches: |
            [
              'main',
              {
                name: 'dev',
                prerelease: 'dev'
              }
            ]
          tag-format: "v${version}"
          additional-packages: |
            ['@semantic-release/commit-analyzer']
          plugins: |
            ['@semantic-release/commit-analyzer']
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
